### ISSUE TITLE
Fehler beim Parsen etc. nicht als Fenster aufpoppen lassen

### ISSUE THREAD

**Issue by alxhu-dev** [ChaoticByte/lurch-dl#34]
**Aktuelles Verhalten:**
Wenn eine fehlerhafte URL eingegeben wird, ploppt ein Fenster mit einer Fehlermeldung auf.

**Vorschlag:**
Schöner wäre es, wenn diese Meldung innerhalb des Fensters (zum Beispiel als Label unter der Textbox) aufploppt, sodass man die Meldung nicht erst wegklicken muss, um die Eingabe zu korrigieren.

Um zu verdeutlichen, was ich meine, hier einmal der Ist-Zustand:
![grafik](https://github.com/ChaoticByte/lurch-dl/assets/32041622/afa85946-24eb-4916-8597-b71fe557836e)

und hier einmal ein in Paint zusammengebasteltes Konzept, was ich ungefähr meine:
![grafik](https://github.com/ChaoticByte/lurch-dl/assets/32041622/1283481d-caf6-4e1a-b5e9-d3904efd0fb3)

**Comment by ChaoticByte** [comment]
Schöne Idee, ich überleg's mir - ist aber vmtl. was für etwas weiter in der Zukunft...

**Comment by ChaoticByte** [comment]
auch hier, siehe https://github.com/ChaoticByte/lurch-dl/blob/discontinued/README.md

Aber süß dass du dir die Mühe gemacht hast ein Proposal zu zeichnen ^^
