### ISSUE TITLE
Verwenden von deaktiverten UI-Elementen mit der Tab-Taste möglich

### ISSUE THREAD

**Issue by alxhu-dev** [ChaoticByte/lurch-dl#35]
**Fehlerbeschreibung:**
Es ist möglich, in deaktiverte Felder mithilfe der Tab-Taste zu landen bzw. deaktivierte Buttons mit der Tab-Taste zu drücken.

**Repoduktionsschritte:**
1. Anwendung starten
2. Feld für Video-URL anklicken
3. Tab-Taste drücken

**Erwartetes Verhalten:**
Deaktivierte Elemente können nicht mit der Tab-Taste fokussiert werden.

(Getestet unter Windows 11)

**Comment by ChaoticByte** [comment]
Ouh, da hab ich wohl was im CSS vergessen ^^

Danke für's melden :D

**Comment by ChaoticByte** [comment]
siehe https://github.com/ChaoticByte/lurch-dl/blob/discontinued/README.md
