### ISSUE TITLE
Beim Leeren des URL-Feldes kommt eine Fehlermeldung

### ISSUE THREAD

**Issue by alxhu-dev** [ChaoticByte/lurch-dl#36]
**Fehlerbeschreibung:**
Wenn man das Textfeld für die Video-URL leert, erscheint eine Fehlermeldung.

**Repoduktionsschritte:**
1. Anwendung starten
2. In Feld für Video-URL klicken
3. Video-URL einfügen
4. woanders hinklicken (sodass das Feld nicht mehr fokussiert ist)
5. Video-URL aus Textfeld entfernen
6. woanders hinklicken (sodass das Feld nicht mehr fokussiert ist)

**Erwartetes Verhalten:**
Ein leeres Feld sollte nicht geparst werden.

(Getestet unter Windows 11)

**Comment by ChaoticByte** [comment]
Ich wusste doch ich hatte was vergessen xD
Danke!
