### ISSUE TITLE
"Abbrechen" bei der Nachfrage bei partiellen Downloads hinzufügen

### ISSUE THREAD

**Issue by alxhu-dev** [ChaoticByte/lurch-dl#37]
Wenn ich einen bereits angefangenen Download fortsetze, kommt diese Meldung:

![grafik](https://github.com/ChaoticByte/lurch-dl/assets/32041622/30983c4d-dd9f-4bec-9deb-7443548c5a9f)

Schön wäre es, wenn in dieser MessageBox noch ein "Abbrechen"-Button existiert, mit welchem ich direkt die Aktion abbrechen könnte (also gar keinen Download starten möchte). Denn zu dem jetzigen Zeitpunkt ist nicht klar, dass "Nein" = "Download neu beginnen" bedeutet.

Noch schöner wäre es, wenn da nicht steht "Ja" und "Nein", sondern "Download fortsetzen", "Download neu beginnen" und "Download abbrechen". Somit ist etwas deutlicher, welcher Button was bedeutet.

**Comment by ChaoticByte** [comment]
Klingt gut, mal schauen inwieweit sich das umsetzen lässt (manche Bebtriebssysteme lassen keine zusätzlichen Buttons zu)

**Comment by ChaoticByte** [comment]
siehe https://github.com/ChaoticByte/lurch-dl/blob/discontinued/README.md

Trotzdem danke für dein Commitment :)
