### ISSUE TITLE
Umstellen der GUI auf Deutsch

### ISSUE THREAD

**Issue by alxhu-dev** [ChaoticByte/lurch-dl#38]
Da Gronkh.tv eine deutschsprachige Seite für einen deutschsprachigen Streamer ist, wäre es schön, wenn die Anwendung ebenfalls ein deutschsprachiges User-Interface besitzt.

**Comment by ChaoticByte** [comment]
Die dadurch entstehende Komplexität würde die mir zur Verfügung stehende Zeit sprengen.
Die GUI komplett auf Deutsch umzustellen ist jedoch eine Möglichkeit die ich im Hinterkopf behalten werde.

**Comment by ChaoticByte** [comment]
siehe https://github.com/ChaoticByte/lurch-dl/blob/discontinued/README.md
