### ISSUE TITLE
Rechtsklick auf URL-Feld öffnet kein Kontextmenü zum Einfügen

### ISSUE THREAD

**Issue by alxhu-dev** [ChaoticByte/lurch-dl#39]
Es wäre schön, wenn sich ein Kontextmenü öffnet, wenn man mit der rechten Maustaste auf das URL-Feld klickt. (Manche Anwender sind es gewohnt, mit bei einem Textfeld "Rechtsklick -> Einfügen" zu drücken, um Daten einzufügen.)

**Comment by ChaoticByte** [comment]
Ist eher ein Bug als eine Suggestion

**Comment by ChaoticByte** [comment]
https://wails.io/docs/reference/options/#enabledefaultcontextmenu

**Comment by ChaoticByte** [comment]
siehe https://github.com/ChaoticByte/lurch-dl/blob/discontinued/README.md
