### ISSUE TITLE
Queue für gedownloadete Videos

### ISSUE THREAD

**Issue by alxhu-dev** [ChaoticByte/lurch-dl#40]
Beim Herunterladen eines Videos wird die gesamte UI gesperrt, solange das Video heruntergeladen wird.

Es wäre schön, wenn ich in der Zeit weitere Videos zum Downloaden "einreihen" könnte, die nach dem abgeschlossenen Download direkt als nächstes heruntergeladen werden.

**Comment by ChaoticByte** [comment]
Vielleicht irgendwann... mal schauen.

**Comment by ChaoticByte** [comment]
siehe https://github.com/ChaoticByte/lurch-dl/blob/discontinued/README.md
