### ISSUE TITLE
Downloadgeschwindigkeit konfigurierbar

### ISSUE THREAD

**Issue by alxhu-dev** [ChaoticByte/lurch-dl#41]
(Das ist bestimmt nicht so einfach umzusetzen ^^')

Es wäre schön, wenn man konfigurieren könnte, mit welcher Downloadgeschwindigkeit man die Videos herunterlädt.

**Comment by ChaoticByte** [comment]
Ist in der CLI bereits möglich

```
 [--max-rate]       The maximum download rate in MB/s - don't set this
                            too high, you may run into a ratelimit and your
                            IP address might get banned from the servers.
                            default: 10.0
```

-> relativ einfach umzusetzen

**Comment by ChaoticByte** [comment]
siehe https://github.com/ChaoticByte/lurch-dl/blob/discontinued/README.md
